env:
  node: true

extends:
  - "airbnb-base"

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0

  plugins:
  - jest
  - testing-library
  - jest-dom

# env:
#   jest: true
#   browser: true
#   es2020: true

# extends:
#   - 'airbnb-base'
#   - 'plugin:jest/recommended'
#   - 'plugin:testing-library/react'
#   - "plugin:jest-dom/recommended"

# parserOptions:
#   ecmaVersion: latest
#   sourceType: module

# plugins:
#   - jest
#   - testing-library
#   - jest-dom

# rules:
#   import/extensions: 0
#   import/no-unresolved: 0
#   no-param-reassign: 0
#   no-console: 0